### ISSUE TITLE
CustAuth with other services(website, forum)

### ISSUE THREAD

**Issue by acertain** [SimpleServer/SimpleServer#117]
It would be extremely useful if there was some way to use custauth logins(so players can register in game and must use mc username) and the permissions list with a website so I could have web-controls and a forum.  i think a read xml file (that simple server only writes to) creation option for this would work( a xml file with username password and group ).

**Comment by dola** [comment]
If you really want to do that you could already read out the simpleserver.nbt file with a nbt utily (one is built in in SimpleServer itself)
But to make it a bit easier I could add a hidden option to activate some mirrored saving in a simple textfile in the format `name=pwhash`. You however have to calculate the hash then with php as it's done by SimpleServer already.

Have a look at [this function](https://github.com/SimpleServer/SimpleServer/blob/master/src/simpleserver/Authenticator.java#L168) to see how it works exactly.
This should be easily possible with e.g. php since it supports sha-256 with the 
`hash ( string $algo , string $data [, bool $raw_output = false ] )` 
function where you set `$algo = 'sha256'`. (More about this [here](http://www.php.net/manual/de/function.hash.php))

Contact me if you got truble with this. I'll try to add the option for 8.3 in a few days. (Got an examn first^^)

**Comment by heapoutofspace** [comment]
There are some NBT libraries for PHP e.g. the one of [TheFrozenFire](https://github.com/TheFrozenFire/PHP-NBT-Decoder-Encoder). To get the groups you currently have to parse the XML which shouldn't be that hard.

Adding a file or even a little command-line tool may be a better solution, we will discuss that after dola's exam.

**Comment by dola** [comment]
ok current plans are:
- output as `playerName=groupId,pwHash`
- list only contains registered players
- update everytime a registerd player changes group or pw and if someone new registers
- output into a textfile into an export folder inside the _simpleserver_ folder
- add an option in the new _config.xml_ to enable the whole thing
- provide code in the wiki to hash passwords (at least in php and java)
