### ISSUE TITLE
group text color is missing

### ISSUE THREAD

**Issue by ehlers299** [SimpleServer/SimpleServer#127]
I know this topic isn't THAT important but it really helps me distinguish between joobs and my friends... A few days ago i finally got CraftBukkit and they are both working fine i also added the multiverse plugin which seems to be doing well also but when i went ingame my text was WHITE..... WHITE! i triple checked the permissions file and everything in there told me i was an admin with the color code a for green but in game i was well you know WHITE!!! please help:()

**Comment by dola** [comment]
can you upload your permissions.xml to [pastebin](http://www.pastebin.com) and give us the link? And maybe you can join us on irc ([irc.eurirc.net#SimpleServer](http://www.mibbit.com/?server=irc.euirc.net&channel=%23SimpleServer)) so we can speak about the issue in detail and maybe test it ourself on your server...

**Comment by ehlers299** [comment]
http://pastebin.com/7rHGS5ej

**Comment by ehlers299** [comment]
also spawnmonsters is set to false but i am still getting monster and no health regen

**Comment by ehlers299** [comment]
Bumpy Bump

**Comment by dola** [comment]
I think it has something to do with a bukkit plugin that somehow changes the text...
We cannot really do anything against this since we cannot influence bukkit. BUT:
with 8.3 the new messageSystem goes live which doesn't need to send any messages to the backgrounded server (bukkit or vanilla) and directly sends them to the players. Like the color won't change anymore. So all you can do now is waiting for the update of SimpleServer. (I would build it for you if this function was fully working but it isn't...)

**Comment by ChironXII** [comment]
Multiverse requires Spawn Monsters to be true, set it to that in ss and then use MV to disable them (Otherwise weird stuff happens).
