### ISSUE TITLE
Enabling useMode forwards /help

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#14]
If this isn't handled by the plugin (which it isn't by Bukkit) the standard server help covers the whole screen.

**Comment by heapoutofspace** [comment]
Maybe we should allow `<command name="blubb" forward />`

**Comment by apirogov** [comment]
you mean `<command name="blubb" forward="true" />`? AFAIK your version is not vaild XML...

Well, thats possible... you mean as a replacement for the hardcoded shouldPassToMod value?

**Comment by heapoutofspace** [comment]
Are you sure that isn't valid? My Bukkit server has no /help message, but there are plugins to add one. In this case hard coding it is really a bad idea.

**Comment by apirogov** [comment]
Well ok then I'll remove that shouldPasstoMod thingy from the interface and add such a setting instead... and yes I'm quite sure that you cant just write `forward` as an attribute without value... when writing XHTML there are some attributes which must be written `attribute="attribute"` to set them, I've never seen just `attribute` which of couse would be more convenient, but not conforming the rules...

**Comment by apirogov** [comment]
I pushed it, and the return value of commandShouldPassToMod is 100% correct (tested it), but I don't know whether the forwarding really happens and I'm not using Bucket, so if it is not working, the problem is somewhere else...

So now all commands that shall be forwarded have to be flagged accordingly in the permissions.xml with `forward="true"`

**Comment by heapoutofspace** [comment]
Thanks. I just started using Bukkit and am will test it.
