### ISSUE TITLE
update all wiki entries for 8.3

### ISSUE THREAD

**Issue by dola** [SimpleServer/SimpleServer#146]
e.g. remove references to _permissions.xml_ and set new ones for _config.xml_.

Maybe add FAQs and bring other sites up to date.

(we would of course appreciate any help of expirienced SimpleServer users)

**Comment by acertain** [comment]
Maybe add a "old" section for outdated help :p

**Comment by The-PC-Tech-Guy** [comment]
Just a comment on how things are progressing on "Simple"server: It seems as if things are getting more complex. Although I like most of the new features (I really wish the new chat thingy would be displayed on the console somehow... at least /local is now visible), the XML format makes things a bit complex. I do understand how it can be nicely organized, but if that's the case, then I highly prefer YAML files. Or you could make a graphic interface. (That would be nice!)

Speaking of config files, I think we should start to consolidate the simpleserver.properties file and the config.xml file, seeing that some of the nodes in the properties file were transferred to the xml file. Or at least simplify both files... I really am not liking how the XML is going...

**Comment by heapoutofspace** [comment]
I don't really see how this update made anything more complex. The XML format is pretty much the same as before just with prettier serializing and incredibly better parsing performance. We splitter the properties for a reason, before you didn't know which settings can be changed while the server is running and which can't.

I will add an option for the XMLSerializer to store some fields in attributes instead of their own tags, it will be less confusing for people not knowing XML at all. And as you might know there is already a little web interface which we want to port and include in the next major version.

**Comment by JakeDiFebo** [comment]
I am happy about this! You wouldn't believe how many times I accidentally clicked that google link instead of GitHub.

**Comment by acertain** [comment]
must update the config group syntax
