### ISSUE TITLE
use of /lock will result in exeptions and disconnect

### ISSUE THREAD

**Issue by QueerCodingGirl** [SimpleServer/SimpleServer#154]
The server is currently in onlineMode=false and verifyNames=false

Minecraft version = 1.8.1
SimpleServer version = 8.3.3

Output at the client:

> Exception: Java.io.IOException: Received string lenght longer then maximum allowed (20>16)

In the server log:

> [SimpleServer] java.io.EOFException
> [SimpleServer] PlayerStream error handling traffic for xxx.xxx.xxx.xxx (a)> 
> [SimpleServer] java.net.SocketException: Broken pipe
> [SimpleServer] ServerStream error handling traffic for xxx.xxx.xxx.xxx (36)
> [SimpleServer] Socket Closed: xxx.xxx.xxx.xxx
> java.net.SocketException: Connection reset
>         at java.net.SocketInputStream.read(SocketInputStream.java:168)
>         at java.net.SocketInputStream.read(SocketInputStream.java:182)
>         at java.io.FilterInputStream.read(FilterInputStream.java:66)
>         at in.a(SourceFile:135)
>         at ma.h(SourceFile:190)
>         at ma.c(SourceFile:10)
>         at ta.run(SourceFile:77)
> 2011-09-20 00:34:45 [INFO] USERNAME lost connection: disconnect.genericReason

**Comment by EightyNine** [comment]
same here :S

**Comment by QueerCodingGirl** [comment]
and with /myarea too

**Comment by dola** [comment]
Is it possible that you're using german as language for the server. (Also habt ihr die sprache des severs auf deutsch gestellt?) If yes, then we were able to find the error causing this and a temporary solution can be found [here in the forum](http://www.minecraftforum.net/topic/309373-software-simpleserver-wrapper-833-181/page__view__findpost__p__8446967). Of course this will be fixed in the next release.

Else it might be helpful if you could join us on irc (see first forum post or faq) and we'll try to help you.

**Comment by QueerCodingGirl** [comment]
you are right, i changed it to 'de'... in 'en' it all work fine. i change it back until it will be fixed.

**Comment by QueerCodingGirl** [comment]
the '/myarea save' command doesnt work... in 'en' and in 'de'
