### ISSUE TITLE
Area permissions

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#2]
Merge from apirogov's repo

**Comment by heapoutofspace** [comment]
@apirogov: In my opinion it would make sense to execute the converter from the server instead of loading the default xml file. I know you don't like legacy code, but I think we could safely remove it after a few weeks.

**Comment by apirogov** [comment]
Done! :)

I removed the previous format converter from options because 1) it was making problems because of it's dependency on PermissionConfig and 2) I think no sane person still uses SimpleServer pre-7.0 or something..

I also removed that PRINT_COMMAND_HELP thing from main... If even I don't know how to invoke it, how would a normal user know how to start it in this mode? If neccessary I can implement a new -h switch (though I don't think it makes sense and there's the README after all)

My conversion class has no dependencies, so it's not interfering with anything else.. so I don't mind even if it stays for some longer time now

**Comment by heapoutofspace** [comment]
Great!

One could invoke the command help by setting the system property PRINT_COMMAND_HELP to true, but I don't think anyone has every done that.

Did I merge everything correctly? There were plenty of conflicts :D

I'm going to clean up my own code a bit and have a quick look at yours, but I think we should be ready for the shiny 8.0 release this week. The whole authentication thing is still missing, I guess that's something I have to implement myself for 8.1.

It seems like spieglpwns wiki is full of spam, so I'm going to move the important pages into the wiki here. This way we'll have a clean wiki maintained by the developers. If other people want to edit it we can still give them the right to do so. Sounds ok?

**Comment by apirogov** [comment]
I looked through the commit and it seemed fine... I hope it really is ^^

And I tried to start it with PRINT_COMMAND_HELP=true java -jar SimpleServer.jar but it didn't work xP but whatever... its gone :D

I thought about suggesting to move the wiki here myself, so yes of couse :) Maybe then I'm going to write a kind-of howto for the permissions.xml and area stuff...

**Comment by apirogov** [comment]
May I merge areapermissions into master? It's going there anyway for the next version and it would allow me to branch off master instead of areapermissions for new stuff^^ (I fear branching off from master now as theres such a big difference between master and areapermissions...)

**Comment by heapoutofspace** [comment]
Sure, go ahead!

**Comment by apirogov** [comment]
Ok, piece of cake :) You've done the annoying part of the job already^^
