### ISSUE TITLE
Idbehold not working 

### ISSUE THREAD

**Issue by Harmfuleffect** [SimpleServer/SimpleServer#20]
Hello. I just recently setup a server and finally got a good wrapper to work, yours :) Thank you. 

With no mods installed for single player nor for multi, I installed your server. I was attempting to reduce the time it takes to mine obsidium and tried using the command Idbehold. The server responds that it is enabled but i do not see any effect. The time it takes to mine obsidium is the same with or without the command enabled. I restarted the server and client and had the same effect. I have given myself rank 5 (owner).

Since you are still testing, I wanted to provide feedback after reviewing the known/closed issues.

Thanks,

HarmfulEffect

**Comment by apirogov** [comment]
This is a known issue since I think... Minecraft 1.2 or 1.3... Notch changed something in the server (maybe as an anti-cheat measure) so that the instant destroying became impossible (at least with the old trick). No one has found a way to work around it so far..

Well, I think idbehold should be deactivated/removed in future versions as long its definitely not working, to not confuse users..

Thanks for your report anyway :)

**Comment by Harmfuleffect** [comment]
Thanks for the info. Believe it or not, I just started playing minecraft at 1.5 and dove in full force. I am all about multiplayer and I found this mode to easy to install and use. Tried a few other wrappers but with no luck.  Think I'll close this issue since its a known prob.
