### ISSUE TITLE
Why are there 2 configuration files?

### ISSUE THREAD

**Issue by bryanburke** [SimpleServer/SimpleServer#201]
One of the things about SimpleServer that I have never understood is its use of 2 separate configuration files, simpleserver/config.xml and simpleserver.properties. Is this duality due to a purposeful separation of certain options or has simpleserver.properties simply fallen through the cracks in the migration to XML config files? Would the contributors be opposed to having all the options migrated into simpleserver/config.xml?

Also, within simpleserver/config.xml itself, are xmlInlineAttributes and xmlPCDATA supposed to be end-user options, or are they only present for testing purposes?

**Comment by heapoutofspace** [comment]
As stated in the [wiki](https://github.com/SimpleServer/SimpleServer/wiki/config.xml#wiki-properties):

```
Unlike the properties in simpleserver.properties those can be changed while the server is running.
```

So all options which can be changed (using /reload) at runtime are in the _config.xml_ file while all others are in _simpleserver.properties_

I put xml options in there because most people didn't like my new syntax. I personally have xmlInlineAttributes disabled and there might be others who use those options.

**Comment by bryanburke** [comment]
Thank you for clearing that up for me. I noticed also that the "difficulty" setting is not in simpleserver.properties. I would guess that this is because the official Minecraft server absolutely requires it to be in its own server.properties. However, I could be wrong about that.

**Comment by heapoutofspace** [comment]
No, the difficulty is really missing. You can patch it if you want to ;)
