### ISSUE TITLE
True Tunnel Pivoting

### ISSUE THREAD

**Issue by nickpoorman** [SimpleServer/SimpleServer#212]
Feature Request:

Be able to specify an already running minecraft server IP address to use this as a true tunnel for pivoting.

Lets say I have a server (A) running behind a firewall that is running the actual minecraft server and another server (B) that is not behind the firewall. Clients cannot connect to Server A, however they can talk to Server B, and Server A can talk to Server B thus SimpleServer could run on Server B and act as a tunnel between the Client and Server A.

Currently I'm doing this with netcat however it seems ridiculous if I'm going to run SimpleServer then I may as well just replace netcat with it.

**Comment by dola** [comment]
The problem is that SimpleServer not only needs a TCP connection to a minecraft server but also command line access (since many commands are issued directly into the console of the minecraft server by SimpleServer)
Even if we would change this behaviour to use e.g. commands sent by a hidden bot that is op on the server we would loose the access to the server output (which is essential). I myself don't know a solution that could solve that problem by only extending SimpleServer, however if you know one feel free to tell us or try to implement it yourself.

So I think for now methods like _netcat_ or maybe an _ssh tunnel_ are better ways to achieve this.

**Comment by kevinpeno** [comment]
@dola with the emergence of rcon in the mc server this should no longer be a problem.

**Comment by acertain** [comment]
@kevinpeno the default rcon is not secure!
mabye a small app on the server w/o simpleserver?

**Comment by kevinpeno** [comment]
@fread2281 nether is the TCP connection.

**Comment by acertain** [comment]
@kevinpeno but auth stuff may be sent through the rcon...

**Comment by kevinpeno** [comment]
@fread2281 currently the custom auth implemented by simple server is sent in a chat message over TCP un-encrypted. Minecraft doesn't support any encryption, period. RCON will suffer in the same way. However, with the way SimpleServer works to talk to the server (typically within a local computer or intranet, as proposed and possible here), there is now more worry of issues than exists now.

Additionally, any auth system that is not supported by the client connecting to the server will suffer the same problems. Minecraft's auth system doesn't suffer from this however because it implements a session ID that the server can verify external to the client.

**Comment by acertain** [comment]
I know, but server to wrapper may be more sensitive.

**Comment by kevinpeno** [comment]
@fread2281 I'm not really sure how since SimpleServer only supports default information. If bukkit adds anything, it'd suffer the same faults. So, I'm not really sure what you are getting at.
