### ISSUE TITLE
/setopt

### ISSUE THREAD

**Issue by kevinpeno** [SimpleServer/SimpleServer#226]
When managing a remote server I must download and edit the config file every time I need to change something. The downloading wouldn't need to happen if user group assignments weren't stored in the same xml file, but that is not the case. Even still, when playing with new configuration options, or on a test server, having a `/setopt` command could be quite useful.

**Example usage:**

`/setopt useWhitelist true` Set the option and save to config file
`/reload` Reload the server to make option take effect. This allows for multiple changes to take place before being applied.

**Comment by bryanburke** [comment]
I like this idea; however, I suggest that the in-game help for the command clearly state that the wiki (or perhaps the included README) should be referenced during its use. Also, incorrect option names should return an error also referencing the wiki or README.

Also, something else to consider: should the command only set an option when used or BOTH set an option and then call the /reload command?

**Comment by ravngr** [comment]
I started coding it up. At the moment it automatically saves after running, I suppose you could get away without this since the values are changed in the server so there's no need to reload, also config.xml will probably be saved at some point (ie. during shutdown).

I also made it do a search if just a key is provided (eg. /setopt auto gives you all the option names that include "auto"). I played with it also printing all the configuration options if no key was provided, but it just floods the chat window so it fairly useless. I'll add a not to consult the wiki/README if users don't know any valid keys.

Two other notes; at the moment if you try and change a boolean value to an interger (/setopt autoSave 5) or vice versa you get an invalid type error, but it's just going off the text values (value.equals("true")). Since there's no way to determine what type a property should be I think this is good for the average case, but I suppose it might cause trouble if you wanted to make "false" the server description or something (probably not a big deal). Secondly, all properties are stored in a HashMap object, which means the keys are case sensitive (due to the nature of hash tables). I got around this by doing an iterative search on the values with .toLowerCase() applied, it's not quite as nice as just a straight hash lookup and the efficiency loss if probably negligible given the number of properties, but still.

Also made it default to group ID 5+, seems like the owner should be able to edit config.xml anyway ;)

**Comment by ravngr** [comment]
Oh and also I could commit to my repo and do a pull request if the other devs want to look it over/modify it before committing.

**Comment by bryanburke** [comment]
@ravngr I think it would be more beneficial to a server operator (and generally safer) if config.xml is saved immediately.

**Comment by ravngr** [comment]
@bryanburke Agreed, I suppose the only time the it would be useful not to is if you wanted to make temporary changes but that would require reworking some other commands to prevent them saving anyway.

**Comment by kevinpeno** [comment]
Hey, thanks for jumping on this. If it is easiest to apply the changes immediately then I'd say go with that. Maybe a little alteration to explicitly save to the config file that way you can quickly revert if you don't like the changes. This would be nice in case you did something silly that caused you to crash the server or get locked out (not sure how, but who knows).

`/config setopt whitelist true` (or use `/setopt`)
`/config save` (if `/setopt` is used, reuse `/save`)
`/config revert` (works like `/reload` to reset config to file based values and, if the above, use `/reload`)

**Comment by ravngr** [comment]
@kevinpeno Yeah that was something I was thinking about, I suppose the only problem is things like /myarea already force a save, so you could end up with weird corner cases. Defiantly something to think about in the future.

Actually something else to consider too, should there be blacklisted fields (implemented as a hard coded list)? Not for security, but just because you can't enter valid values for in the chat window for fields like msgFormat which includes escape characters for colour.

Apart from that I think it's ready to commit.

**Comment by kevinpeno** [comment]
@ravngr, good point. I was not aware of that. I'd go with a whitelist of options and phase them in over time. That way anything new can get tested before being accepted as part of that list.

**Comment by ravngr** [comment]
Just made it look for escape characters in the previous value, figured this saves having to allow/veto everything that may be added to config.xml, but of course if it turns out to not be enough then a white/blacklist can probably easily be added.

**Comment by kevinpeno** [comment]
Awesome, thanks.
