### ISSUE TITLE
Boat + local = fail

### ISSUE THREAD

**Issue by kevinpeno** [SimpleServer/SimpleServer#227]
If you try to type in local channel while in a boat it does not work. Says "no one is around to hear you." Very odd.

**Comment by ravngr** [comment]
This probably occurs because while you're in a boat SimpleServer reads the player's co-ordinates as 0, -999, 0 or something to that effect, so there literally is nobody around there. You'll also see the same thing if you use /area, which will return the wrong area. Not sure why this happens, possibly the player coordinate while in a vehicle is contained elsewhere (like the player is parented to the boat entity or something, so the position is calculated from that)?

**Comment by bryanburke** [comment]
Lol. You gotta love open source. I bet Microsoft isn't getting bug reports
like this.
