### ISSUE TITLE
Can't acces my own server.

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#228]
Ok here is the problem. Im using windows 7 64bit. I can't acces my own server, neither can my friends. Only way I am able to login to my server is through 127.0.0.1:25565. "localhost" and my public IP doesn't work. I have portforwarded my static IP 192.168.0.10 with port 25565, and tried to run my simple server wrapper with administrative rights and compability mode neither one helps. I have also tried to disable my windows firewall and anti-virus ( microsoft security essentials ). Launcher bat gives me all kind of errors but mostly "IP Connction from xx.xx.xx.xx! Socket closed: xx.xx.xx.xx". These are main things in my simpleserver.properties file: 

internalPort=25566
ipAddress=0.0.0.0
port=25565
white-list=false

and in server.properties I got:

server-ip=127.0.0.1
server-port=25566
white-list=false

and yes I have white listed myself in every white-list file i have found. Also I have tried deleting everything, and doing as said in manual: Run .bat file and join server through my public IP without changing anything, also doesn't work.

When I use Minecraft_Server.exe provided on official minecraft server everything works perfect. So can anybody tell me what is it that I am doing wrong with simple server? Need help desperately. Thanks in advance.

**Comment by shanet** [comment]
You can't use your public IP to connect to a server on your LAN from inside your LAN. Use the internal IP of your server from inside your LAN. This is not an issue with SimpleServer.

**Comment by ghost** [comment]
How about other players then? They cant login either

**Comment by shanet** [comment]
I'm sorry, I read that as " I can't acces my own server, but my friends can". I'm a Linux person so I'm not terribly knowledgeable in the Windows department nor am I a developer of SimpleServer, so I'm not going to be of much help. However, when you say that "Launcher bat gives me all kind of errors", what are these errors? Can you post them? Your problem may lie in there.

**Comment by ghost** [comment]
Well sometimes I get Protocol error, sometimes "Took too long to log in". That is errors my launcher gives. Minecraft on the other hand gives errors like "Connection lost, Protocol error, Server returned invalid key etc."

**Comment by shanet** [comment]
What version of Minecraft are you running? The current pre-compiled downloads of SimpleServer do not support Minecraft 1.1 (the current version) yet. You'll need to compile the source yourself if you want to use it with Minecraft 1.1. You could probably find a current build floating around somewhere, but I don't think the devs would appreciate me linking to one here since they probably have their reasons for not updating the pre-compiled downloads yet.

**Comment by ghost** [comment]
Im running Minecraft version 1.1 and my Simple server version is 8.3.4. So this is my problem?

**Comment by shanet** [comment]
Yes, that version only works with Minecraft 1.8-beta. The forum thread occasionally updates with an RC build for the current version of MC (http://www.minecraftforum.net/topic/309373-software-simpleserver-wrapper-834181/), but there isn't one for MC 1.1 yet.

If you want to use SimpleServer with MC 1.1 you'll need to download the source and compile it yourself with Ant and a Java compiler. That's what I did and its been working wonderfully so far.

**Comment by ghost** [comment]
Could you email me files I need? Because im not that good at Java. I would appriciate that. My email is Mangoxanim@hotmail.com

**Comment by ravngr** [comment]
Not sure when the next release is, I guess sadimusi decides since he has the thread on Minecraft Forum. In the mean time I setup automatic nightly builds at http://dev.ravngr.com/SimpleServer/ (you'll probably want the zip files) no guarantees that it's stable though, since it is built straight from the repository. Also note that while it makes new files every day, there may not be any actual changes (work in progress...), best off watching the commit log for the repo if you want to know when to update.

**Comment by heapoutofspace** [comment]
Sorry, I always forget to actually release it after putting the RC on the forum.

**Comment by bryanburke** [comment]
Issue resolved.
