### ISSUE TITLE
Issues With perms

### ISSUE THREAD

**Issue by ghost** [SimpleServer/SimpleServer#229]
Ok, so heres what my problems are:

-I cant use the // commands for world edit or any other bukkit commands
     (and yes I did the forwardUknownCommands="true" thing for my groups 4 & 5
- Even though I have set my group for my character to group 5 which is owner, I cant use /op command or any bukkit commands even though I did the forwardUnknownCommands="true" thing for that group. Please help me, I am liking this wrapper so far, but I'm getting really frustrated. Thanks.

**Comment by kevinpeno** [comment]
One thing simpleserver doesn't do is add people to the op file. Thus, any modification on the MC or bukkit server side that requires OP will require the user be placed in the op file manually. This is probably exactly what your problem is.

Might be nice if SimpleServer had an attribute for groups like `op=true` to automatically add and remove people as they shuffled through groups.

**Comment by bryanburke** [comment]
Does the Minecraft server need to be restarted when players are added to/subtracted from ops.txt?

**Comment by ghost** [comment]
This isn't about the op issue. What I REALLY want how with is why I cannot as server owner group have access to bulking commands een though I have enabled command forwarding. This is the most pressing issue at the moment.

**Comment by kevinpeno** [comment]
@ironsmith123 If you have commands set to passthrough, which you said you do, then it is related to one of two things that I am aware of. If you are using a permissions system on the bukkit side it is setup incorrectly. If not, then op is not set for the user in question and the command requires it. Anything else will need more information to help with fixing.

@bryanburke I think that a user added manually will get it next time they relog (it works this way for whitelist.txt). However, you could always just send `/op username` to the server when a user is set to a group that has `op=true`.

**Comment by ghost** [comment]
So what exactly do you suggest I do?

**Comment by kevinpeno** [comment]
@ironsmith123 that kind of depends on your server setup. Do you use bukkit permissions? If no, is your owner in the op.txt file? If yes, what is the error you get?

**Comment by ghost** [comment]
There is no "error". It's just that even though my character has owner rank using the simple sever perms, it won't let me use any command associated with bukkit. I don't use bukkit perms, I use simple server.

**Comment by kevinpeno** [comment]
@ironsmith123 is your user in the op.txt file?

**Comment by ghost** [comment]
Yes

**Comment by sk9c00** [comment]
Is it possible that because you don't have a permission plugin for bukkit enabled or activated, that worldedit automatically implemented its own built-in permissions system. Check your logs, because I don't think worldedit would recognize simple server permissions lol... All I'm saying is a possibility of the causes of the problem.

**Comment by ghost** [comment]
But I want to use simple servers perm system........=/

**Comment by sk9c00** [comment]
What you can do is install a bridge perms... that acts as a node...

On Wed, Feb 1, 2012 at 7:59 AM, ironsmith123 <
reply@reply.github.com

> wrote:
> 
> But I want to use simple servers perm system........=/
> 
> Sent from my iPhone
>

**Comment by ghost** [comment]
I've gone back to just plain bukkit, I might switch back later, thanks, you can close this issue now.........
