### ISSUE TITLE
Server backgrounding

### ISSUE THREAD

**Issue by dmgening** [SimpleServer/SimpleServer#27]
It will be really great if you add command line option for server to go background, since we have rcon and telnet we don't really need server to stay in foreground to interact with it. I having a lot of troubles trying to write init.d script for server, and using GNU\Screen not really what I want.

Anyway you have nice wrapper, thanks for working on it.

**Comment by vorpalhex** [comment]
Depending on the distro, backgrounding is accomplished differently. Since this is java based, it's possible to build a daemon mode, but it's not very efficient or clean. 

It is much better if you can use your distro's native backgrounding abilities, either through your init.d library (RedHat/Cent) or Screen (works on anything).  I personally use Screen out of preference, but there are several other solutions as well.

For an init.d script using screen, use "screen -d -m ./launch.sh" to start, and "kill `screen -r | awk '{print $1}'`" to stop it (if you have more then one server or more then one screen'd process, just add in a grep of course).

To use RedHat/Cent's init.d library, look for a sample init script. 

You may also just want to use upstart.

**Comment by heapoutofspace** [comment]
Are you sure stopping the server like that performs a proper server shutdown? Personally I use telnet to shut it down and only kill it if this fails.

**Comment by vorpalhex** [comment]
That should issue a proper SIGINT which calls the shutdown hook which passes the 'stop' command to the server and closes everything gracefully. If your distro isn't playing nice, you can try passing a lower SIGINT...

**Comment by heapoutofspace** [comment]
Using start-stop-daemon seems to work fine. I'll close this one but we should add a tutorial and an example init script to the wiki sometime.
