### ISSUE TITLE
Generator Settings not passed to server.properties file

### ISSUE THREAD

**Issue by Lockhead** [SimpleServer/SimpleServer#280]
I want to build a superflat server and set up the simpleserver.properties in the following way: https://gist.github.com/4014271
After starting the server the content of my server.properties looks like this:
https://gist.github.com/4014267

**Comment by felixwiemuth** [comment]
The setting was [introduced](http://www.minecraftforum.net/topic/1530194-14-serverproperties-file-generator-settings/) with 1.4.2, right? So we probably didn´t adapt that. I´ll take a look.
**EDIT:** Did you add the option manually to simpleserver.properties or is `generator-settings=` already there in a fresh setup?
You cannot simply add things to `simpleserver.properties`, because SimpleServer only supports what is there! If new options for `server.properties` are introduced, we have to add them as well.

**Comment by Lockhead** [comment]
I added it manually because I only upgraded an existing setup and wanted to recreate the world with these new settings. And yes it's new in the 1.4.x realeases

PS: it is normal that ne minecraft_server.jar overwrites the server.properties files after startup? if I watch cat the file I see it change for a second or so, with the simple server header and shortly after that there is the already posted version there

**Comment by Lockhead** [comment]
Tried a workaround with write protection of server.properties, didn't helped, server crashed... :-(

**Comment by felixwiemuth** [comment]
Please read the FAQ in our wiki with the title _I'm trying to change my server settings in server.properties, but it's not working?_.

**Comment by Lockhead** [comment]
I know that the file is overwritten, that's the reason I tried to write protect it.

But in the mean time I decided to delete everything and start with a fresh install and it seems to work. generator-settings is now copied to server.properties file. I later figured out, that I had an error in my config. LevelType has to be "FLAT" and not "SUPERFLAT" and I now think that was also the initially reason why it didn't worked. So I close this here now.
