### ISSUE TITLE
"cannot place block" on buttons and food

### ISSUE THREAD

**Issue by simesy** [SimpleServer/SimpleServer#291]
SS 8.4.7
MC 1.4.6

I have this in my config

<allblocks place="3+" destroy="3+" use="1+"/>

And I have discovered three bugs/problems with players less than level 3.
1. They cannot eat food
2. They cannot push buttons
3. They CAN remove item frames (nothing drops)

I verified the 3rd one, by logging out and in as a different user.

Any thoughts appreciated
Si

**Comment by simesy** [comment]
My XML got munged, let's try that again

```
<allblocks place="3+" destroy="3+" use="1+"/>
```

**Comment by simesy** [comment]
I managed to allow food eating with 

```
    <block id="282,297,319,320,335,354,357,360,363-367,390-396" place="1+"/>
```

**Comment by ginbot86** [comment]
The settings you have are similar to my setup; the item IDs for food is set so that players can eat food. That said, the reason you needed the block-place permission is because if a player is looking at a block (ie. the hitbox is visible) then SimpleServer interprets it as a block placement.

As for item frames and paintings, they aren't blocks. They're entities much like mobs or players in the game. So far, I haven't found any native protections in SimpleServer to prevent damage to item frames and such.

**Comment by simesy** [comment]
This is my updated block whitelist which now includes buckets, blocking with swords, apples and potions.

`<block id="260-261,267-268,272,276,282,283,297,319,320,325,335,344,349-350,354,357,360,363-367,373,390-396" place="1+"/>`
