### ISSUE TITLE
Is placing water/lava blocked by default?

### ISSUE THREAD

**Issue by simesy** [SimpleServer/SimpleServer#292]
First, I hope you don't mind me posting these questions here. Reading/searching the 4000+ page forum thread on minecraftforum does my head in :)

I notice that my players get "you cannot place this block here" with water and lava. I didn't configure that, I don't think. Is that to stop griefing the way Bukkit does it? If so, why would they be allowed to place TNT and not water/lava?

Also, is there a way to turn it off?

**Comment by ginbot86** [comment]
I've been a long-time user of SimpleServer and haven't taken a look at a fresh installation's default configuration files yet.

SimpleServer is a very configurable piece of software. If you don't like those permissions, change them. You can see which data value corresponds to what by clicking this link: http://minecraftwiki.net/wiki/Data_values

**Comment by simesy** [comment]
There is nothing in the default config about these blocks. I examined the code but wasn't able to determine much about how the restriction was being applied. It would be great to be a Java dev :P. That's why I'm wondering if I'm on drugs or if there is some built in default that defines these blocks that I can override.

**Comment by simesy** [comment]
Just to reiterate, there is no default config related to the data values. I grepped the code. So unless they are classified in some other way...

**Comment by felixwiemuth** [comment]
For your consolation: even as an experienced java developer it is not easy to find something out by looking at the code if you didn´t write it yourself - SimpleServer is a quite complex software with developers coming and going ;).
So I can only guess now, too.

I do not think there is something "built in" because that would be a very bad software design and SimpleSevrer isn´t that bad :).
If something is configurable, you should find it in the wiki, the keyword is _permissions_ inside [config.xml](http://github.com/SimpleServer/SimpleServer/wiki/config.xml). I think the wiki is quite detailed on [configuration](http://github.com/SimpleServer/SimpleServer/wiki/Configuration).

So as I cannot find this "you cannot place this block here" text in the whole SimpleServer project we probably can exclude an intentional behaviour of SimpleServer.
Are you using vanilla Minecraft software? If so, the trouble seems to be there or a missing adaptation of SimpleServer to this behavior.

### Addition

The only permission in the default `config.xml` is

```
<blocks allowPlace="1+" allowDestroy="1+" allowUse="1+">
      <block id="7" allow="-" />
</blocks>
```

and this is for bedrock (ID 7).

**Comment by simesy** [comment]
Woohoo! I was totally on the wrong track. The problem wasn't placing water/lava, it was ... _drumroll_ ... using a bucket.

So my problem was related to my other problem where players couldn't eat food. The solution is here:
https://github.com/SimpleServer/SimpleServer/issues/291#issuecomment-12034683
