### ISSUE TITLE
New modding "API"

### ISSUE THREAD

**Issue by heapoutofspace** [SimpleServer/SimpleServer#3]
Notch just announced to publish the source code of minecraft to registered mod developers. Does a network wrapper like SimpleServer even make sense anymore? I don't want SimpleServer to disappear, but we should think about where it's place in the server mod ecosystem is.

**Comment by apirogov** [comment]
As I understand these "legal" mods may be commercialized by Mojang, while the developers themselves are quite restricted in their rights..

SimpleServer has no license agreements with Mojang and therefore stays completely free and open.

So I think we should just continue like before, until SimpleServer might become obsolete, meaning the vanilla server having all the features SimpleServer offers, because of some "legal mod".

On the other hand I'm sure some information (if not the whole source) from the "trusted" developers will leak sooner or later, maybe improving our understanding of the Protocol etc. (when someone e.g. just fills in the blanks in the developer wiki, which would be a violation, but very unlikely to be tracked down) - That may ease the job of keeping SimpleServer up to date without having to sign some agreement...

**Comment by vorpalhex** [comment]
We may want to start really pushing the natural features of a proxified
wrapper, such as expanding into a reverse proxy, and being able to build a
spoke and hub network to all connect to a single server.

I know personally, I'm still going to be using SimpleServer on all my
minecraft servers.
