### ISSUE TITLE
Disconnected after using redstone switches

### ISSUE THREAD

**Issue by zackj191** [SimpleServer/SimpleServer#30]
It seems on my server people keep getting the error of:

"Internal exception: java.IOException: Received string length is less than zero! Weird string!"

It seems to happen when people use redstone switches (pressure plates, levers, buttons, etc.).  However it doesn't always happen immediately, but it seems to occur within a couple seconds of using the switch.

Picture of the error:
http://imageshack.us/photo/my-images/36/crashp.png/

**Comment by dola** [comment]
Thanks for the report :)
That is the same issue we had yesterday and was fixed with the update to 8.1.0 beta from yesterday evening. Simply download the newest version (https://github.com/downloads/SimpleServer/SimpleServer/SimpleServer.zip) and try again. The problem then should no longer occur.

I close this issue for that. If it occurs again (even with 8.1.0 beta) pleas report and reopen.
