### ISSUE TITLE
Minecraft 1.7.2

### ISSUE THREAD

**Issue by bioxz** [SimpleServer/SimpleServer#314]
Minecraft 1.7.2 is out, including a "Large protocol rework" (http://wiki.vg/Protocol_History#13w41a)

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/SimpleServer/commits/protocol

In progress, will merge into final SS repo when done.

**Comment by bioxz** [comment]
Fantastic to hear that!

Should this issue not remain open until it is resolved?

**Comment by iBotPeaches** [comment]
Maybe, but I'm not going to.

SS is down to maybe one/two active dev's. The bug tracker here has bugs that 1-3 years old. Its not a good indication of what actually works/doesn't. The entire tracker should be gone through or just completely cleared out. Since its obvious its broken in 1.7.x, it doesn't really need an active report.

If you want to watch the status, I'd recommend joining our IRC channel #SimpleServer on EUIRC (irc.euirc.net), where we have daily conversations.
