### ISSUE TITLE
Permissions.xml

### ISSUE THREAD

**Issue by legoracer171** [SimpleServer/SimpleServer#42]
How do you change your rank in permissions?

**Comment by dola** [comment]
- If you already are an admin use the `/setgroup PLAYER GROUP` command. (replace PLAYER with the name of the player and GROUP with the group id - e.g. 5 for owner, 4 for admin, 3 for mod etc.)
- If not you have to go the harder way over the _permissions.xml_ file found in the _simpleserver_ folder:
  -  Long answer: (which only looks shorter)
    Try to read and understand this [Guide on _permissions.xml_](https://github.com/SimpleServer/SimpleServer/wiki/Permissions.xml) or at least this [FAQ about how to make one admin](https://github.com/SimpleServer/SimpleServer/wiki/Faq).
  -  Short answer:
    Insert this line `<player name="younickname" group="5" />` into the `<members>` section of _permissions.xml_. (Use Notepad to edit the file and replace _yournickname_ by your nickname and maybe 5 with the specific rank you want to give) After that type `reload` into the server console to reload the changes.

If this does not help you may join us on [IRC](http://www.mibbit.com/?server=irc.euirc.net&channel=%23SimpleServer) or write into the [forum thread](http://www.minecraftforum.net/topic/309373-software-simpleserver-wrapper-811-beta-165/).

**For future questions please use either the forum or join us on IRC since this platform is thought to be a place to report issues or feature plans and not for support**

**Comment by vorpalhex** [comment]
Windows server? If so, are the execute, write and read permissions set for
"everyone"?  Also, is the file actually present? You need to launch
simpleserver once first...
On May 30, 2011 9:23 AM, "legoracer171" <
reply@reply.github.com>
wrote:
