### ISSUE TITLE
Define chestpermission if in two areas

### ISSUE THREAD

**Issue by dola** [SimpleServer/SimpleServer#63]
Currently every 2-blocks-wide chest where one block is inside an area and one outside has a non consistent usage permission. (The block inside the one from the inside area and the one outside the other which can be different)
In such a case only one permission should apply to both blocks and the whole chest.

**Comment by ghost** [comment]
This should be fixed because the items can be accessed from the unlocked side and all the items can be taken, which is what the area permissions should stop. The other side also needs to get the area's destroying group permission (who can destroy it), because otherwise the person can just destroy the chest to get the items without opening it.

**Comment by dola** [comment]
so the higher restricting rule should apply...

**Comment by ghost** [comment]
What about, if two player make their areas right next to each other and then they make 'blocking' rules for the other player and build the chest so that it is a 2-block chest which has one block in one area and other block in the other area. Do neither of the players can access the chest or both of them or what happens?
