### ISSUE TITLE
Add a optional invincible tools

### ISSUE THREAD

**Issue by sveiniz** [SimpleServer/SimpleServer#77]
I have played on some servers and seen on a few that they have invincible tools. To have this as an option in the serverprops or something would be pretty nice! 

This is actually one of the greatest features I have had on a server!

**Comment by heapoutofspace** [comment]
If you are talking about undestroyable tools, we can't really do that. You can however get pretty good tools with the new give command: `/give goldpick:-30000` gives you a golden pickaxe with 30033 uses ;)

**Comment by sveiniz** [comment]
Okei, someone told me once; Make sceptics into belivers! So it isn|t possible at all?

**Comment by ghost** [comment]
Well, the problem is that Simple Server is a wrapper, it doesn't really change the way game runs. It just looks at the code that is passing through. I don't really think that it is possible for Simple Server to do that...
I could suggest you to use [this](http://forums.bukkit.org/threads/inactive-antibreak-v1-40-make-tools-indestructible-602.472/) Bukkit plugin.
