### ISSUE TITLE
Whitelists and waypoints

### ISSUE THREAD

**Issue by wesleyjg** [SimpleServer/SimpleServer#94]
Setting waypoints on a whitelisted server doesn't work because the teleporter bots arent whitelisted.
Perhaps theres a fix I'm not finding.

**Comment by ghost** [comment]
This is actually a big bug without no current fix.

The waypoints, just as the new special give command for colored wool and other damage items and home teleports do _not_ work on a whitelisted server. The problem is that the server checks if the player (in this case the teleporter bot) is on the whitelist and, of course, the bot isn't there so he is not allowed to join.
You cannot whitelist all the teleporter bots, because each time one joins, he joins with a different name.

The only way (I can think of) is for us to rewrite the white-list authorization too, so that it is handled in the same class where we handle other authentication and make it work somewhat like the `online-mode`.

**Comment by wesleyjg** [comment]
Thanks for the quick response and the information. Well, I fixed it by simple unwhitelisting my server. Whitelist isnt really needed with guest permissions.

**Comment by ghost** [comment]
That is true, but it isn't really a bug-fix, it is more like a way to ignore it, so it still needs to be fixed.

**Comment by heapoutofspace** [comment]
This shouldn't actually be a problem because SimpleServer has it's own whitelist and the "real" server is never in whitelist mode. I'll have a look at it.

**Comment by wesleyjg** [comment]
perhaps I did the whitelist wrong

**Comment by heapoutofspace** [comment]
Look at the _server.properties_ file, is whitelist set to true there?
